name: PR Agent Commands

on:
  issue_comment:
    types: [created]

jobs:
  pr_agent_commands:
    if: |
      github.event.issue.pull_request &&
      github.event.sender.type != 'Bot' &&
      startsWith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: the-pr-agent/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.PR_AGENT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_BASE: "https://api.openai.com/v1"
          config.model: "openai/gpt-4o-mini"
